### ISSUE TITLE
Improvements required

### ISSUE THREAD

**Issue by Hiteshm01** [porchezhiyan/DatabaseServer#1]
There are couple of things that needs to be done here.

Output is not a valid json string. 
All json validators, parsers will work only if input json is valid. Try going through http://json.org/example.html to understand what is valid json.

After this, try understanding how to build json systematically (and not by string concatenation) via help urls like this http://stackoverflow.com/questions/23110383/how-to-dynamically-build-a-json-object-with-python.

**Comment by porchezhiyan** [comment]
thank you sir for the suggestions.i have updated the code again, please see it and tell whether i have made the required changes...

**Comment by Hiteshm01** [comment]
It is okay to start with this now. Try adding database connection and writing APIs which can be used to read content of database.
